version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - .:/app
      - go_modules:/go/pkg/mod
    environment:
      - APP_ENV=dev
    ports:
      - "3000:3000"

volumes:
  go_modules: