version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutribox-api
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_ENV=${APP_ENV}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
    networks:
      - nutribox-network
    restart: unless-stopped
    command: /app/api-server

  postgresdb:
    image: postgres:16-alpine
    container_name: nutribox-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutribox-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  nutribox-network:
    driver: bridge